### ISSUE TITLE
U-boot for the new WRT3200ACM Winbond Flash?

### ISSUE THREAD

**Issue by gazaai** [nitroshift/wrt1900ac#3]
Hi nitroshift,

Would you be willing to create a u-boot image for the new Winbond Flash found on the latest WRT3200ACM models?

The current one v0.0.4 does not run on the Winbond NAND.
The version that came with it was v1.0.0 which doesn't seem to be anywhere on the internet yet.
And as OpenWRT does not run on the Winbond WRT3200ACM yet no one can back it up.

Thanks

**Comment by gazaai** [comment]
New files are here:

https://github.com/ValCher1961/McDebian_WRT3200ACM/tree/master/recovery-uboot

For anyone looking.

**Comment by JW0914** [comment]
This has been added to the [Corrupt Bootloader Environment](https://wiki.openwrt.org/toh/linksys/wrt_ac_series#corrupt_environment_recovery) troubleshooting section in the WRT AC Series wiki
